"""
Export config analysis results to CSV and KConfig format.

CSV: machine-readable, importable to spreadsheets
KConfig: human-readable dependency description using Linux Kernel config language syntax
"""

from __future__ import annotations

import csv
import re
from io import StringIO
from pathlib import Path

from .models import ConfigParam, ConfigDependency


def export_csv(
    configs: list[ConfigParam],
    dependencies: list[ConfigDependency],
    output_dir: str | Path,
) -> dict[str, str]:
    """Write configs.csv and dependencies.csv to output_dir.

    Returns dict of filename -> absolute path.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    paths = {}

    # configs.csv
    cfg_path = out / "configs.csv"
    with open(cfg_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(ConfigParam.CSV_HEADERS)
        for c in sorted(configs, key=lambda x: x.qualified_name):
            w.writerow(c.csv_row())
    paths["configs.csv"] = str(cfg_path)

    # dependencies.csv
    dep_path = out / "dependencies.csv"
    with open(dep_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(ConfigDependency.CSV_HEADERS)
        for d in sorted(dependencies, key=lambda x: (x.source_config, x.target_config)):
            w.writerow(d.csv_row())
    paths["dependencies.csv"] = str(dep_path)

    return paths


def export_csv_string(
    configs: list[ConfigParam],
    dependencies: list[ConfigDependency],
) -> str:
    """Return CSV content as a single string (for MCP tool output)."""
    buf = StringIO()
    buf.write("=== configs.csv ===\n")
    w = csv.writer(buf)
    w.writerow(ConfigParam.CSV_HEADERS)
    for c in sorted(configs, key=lambda x: x.qualified_name):
        w.writerow(c.csv_row())

    buf.write("\n=== dependencies.csv ===\n")
    w = csv.writer(buf)
    w.writerow(ConfigDependency.CSV_HEADERS)
    for d in sorted(dependencies, key=lambda x: (x.source_config, x.target_config)):
        w.writerow(d.csv_row())

    return buf.getvalue()


# ── KConfig export ──────────────────────────────────────────────────────────

def export_kconfig(
    configs: list[ConfigParam],
    dependencies: list[ConfigDependency],
    output_dir: str | Path,
    project_name: str = "project",
) -> str:
    """Generate a KConfig-style description of all configs and dependencies.

    Returns the path to the written .kconfig file.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    kconfig_path = out / f"{_sanitize(project_name)}.kconfig"

    content = generate_kconfig(configs, dependencies, project_name)
    kconfig_path.write_text(content, encoding="utf-8")
    return str(kconfig_path)


def generate_kconfig(
    configs: list[ConfigParam],
    dependencies: list[ConfigDependency],
    project_name: str = "project",
) -> str:
    """Generate KConfig content as string."""
    # build dependency lookup: target -> list of deps
    deps_by_target: dict[str, list[ConfigDependency]] = {}
    for d in dependencies:
        deps_by_target.setdefault(d.target_config, []).append(d)

    # build reverse lookup: source -> list of targets it forces
    selects_by_source: dict[str, list[ConfigDependency]] = {}
    for d in dependencies:
        if d.relationship_type in ("DIRECT_OVERRIDE", "MUTUAL_EXCLUSION"):
            selects_by_source.setdefault(d.source_config, []).append(d)

    # group configs by struct
    by_struct: dict[str, list[ConfigParam]] = {}
    for c in configs:
        parts = c.qualified_name.split(".", 1)
        struct = parts[0] if len(parts) > 1 else "general"
        by_struct.setdefault(struct, []).append(c)

    lines: list[str] = []
    lines.append(f"# KConfig description for {project_name}")
    lines.append(f"# Auto-generated by cpp-analyzer config dependency analysis")
    lines.append("")

    for struct_name, struct_configs in sorted(by_struct.items()):
        lines.append(f'menu "{struct_name}"')
        lines.append("")

        for cfg in sorted(struct_configs, key=lambda x: x.name):
            kconfig_type = _map_type(cfg.config_type)
            symbol = _to_kconfig_symbol(cfg.qualified_name)

            lines.append(f"config {symbol}")
            lines.append(f'    {kconfig_type} "{cfg.description or cfg.name}"')

            # default
            if cfg.default_value is not None:
                default_val = _format_default(cfg.default_value, kconfig_type)
                lines.append(f"    default {default_val}")

            # range
            if cfg.min_value is not None and cfg.max_value is not None:
                lines.append(f"    range {cfg.min_value} {cfg.max_value}")

            # enum values as comment (KConfig doesn't have native enum)
            if cfg.enum_values:
                lines.append(f"    # enum: {cfg.enum_values}")

            # CLI flag
            if cfg.cli_flag:
                lines.append(f"    # cli: {cfg.cli_flag}")

            # ifdef guard
            if cfg.ifdef_guard:
                lines.append(f"    depends on {cfg.ifdef_guard}")

            # dependencies: what this config depends on
            target_deps = deps_by_target.get(cfg.qualified_name, [])
            for dep in target_deps:
                if dep.relationship_type == "DIRECT_OVERRIDE":
                    cond = _dep_to_kconfig_condition(dep)
                    if dep.forced_value:
                        lines.append(f"    default {_format_default(dep.forced_value, kconfig_type)} if {cond}")
                    else:
                        lines.append(f"    depends on {cond}")
                elif dep.relationship_type == "MUTUAL_EXCLUSION":
                    source_sym = _to_kconfig_symbol(dep.source_config)
                    lines.append(f"    # mutual exclusion: reset by {dep.source_config}")
                    if dep.forced_value:
                        lines.append(f"    default {_format_default(dep.forced_value, kconfig_type)} if {source_sym}")
                elif dep.relationship_type == "CASCADE":
                    cond = _dep_to_kconfig_condition(dep)
                    if dep.forced_value:
                        lines.append(f"    default {_format_default(dep.forced_value, kconfig_type)} if {cond}")
                elif dep.relationship_type == "AGGREGATION":
                    lines.append(f"    # aggregated by: {dep.source_config}")
                    if dep.forced_value:
                        lines.append(f"    default {_format_default(dep.forced_value, kconfig_type)} if {_to_kconfig_symbol(dep.source_config)}")

            # selects: what this config forces on others
            source_deps = selects_by_source.get(cfg.qualified_name, [])
            for dep in source_deps:
                target_sym = _to_kconfig_symbol(dep.target_config)
                if dep.source_condition:
                    lines.append(f"    # when {dep.source_condition}: forces {dep.target_config} = {dep.forced_value}")
                else:
                    lines.append(f"    select {target_sym}")

            # source location
            if cfg.defined_file:
                lines.append(f"    # defined: {cfg.defined_file}:{cfg.defined_line}")

            lines.append("")

        lines.append("endmenu")
        lines.append("")

    return "\n".join(lines)


# ── KConfig helpers ─────────────────────────────────────────────────────────

def _sanitize(name: str) -> str:
    return re.sub(r'[^a-zA-Z0-9_]', '_', name)


def _to_kconfig_symbol(qualified_name: str) -> str:
    """Convert 'jpeg_compress_struct.optimize_coding' -> 'JPEG_COMPRESS_STRUCT__OPTIMIZE_CODING'"""
    return re.sub(r'[^a-zA-Z0-9]', '_', qualified_name).upper()


def _map_type(c_type: str) -> str:
    """Map C type to KConfig type."""
    t = c_type.lower().strip()
    if t in ("bool", "boolean", "_bool"):
        return "bool"
    if t in ("int", "unsigned int", "long", "short", "size_t",
             "unsigned", "unsigned long", "JDIMENSION"):
        return "int"
    if "char" in t and "*" in t:
        return "string"
    if t in ("float", "double"):
        return "int"  # KConfig has no float; use int
    # enum types
    if t.startswith("j_") or t.startswith("J_"):
        return "int"  # represent enums as int with comment
    return "string"


def _format_default(value: str, kconfig_type: str) -> str:
    """Format a default value for KConfig syntax."""
    v = value.strip()
    if kconfig_type == "bool":
        if v.upper() in ("TRUE", "1", "YES"):
            return "y"
        if v.upper() in ("FALSE", "0", "NO"):
            return "n"
        return v.lower()
    if kconfig_type == "string":
        if not v.startswith('"'):
            return f'"{v}"'
    return v


def _dep_to_kconfig_condition(dep: ConfigDependency) -> str:
    """Convert a dependency condition to KConfig 'if' expression."""
    source_sym = _to_kconfig_symbol(dep.source_config)
    cond = dep.source_condition.strip()
    if not cond:
        return source_sym

    # "== 12" -> "SOURCE = 12"
    m = re.match(r'(==|!=|<|>|<=|>=)\s*(.+)', cond)
    if m:
        op = m.group(1)
        val = m.group(2).strip()
        kconfig_op = "=" if op == "==" else op
        return f"{source_sym} {kconfig_op} {val}"

    return source_sym
